# Setup
title:        멋쟁이사자처럼 at 한양대학교 ERICA
tagline:      강의자료
baseurl:      "http://hyuerica.likelion.org/lecture"
paginate:     1

# About/contact
author:
  name:       Jeewoo Yoon
  url:        https://yoonjeewoo.github.io

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown